[language-server]
godot = { command = "nc", args = ["127.0.0.1", "6005"] }

[[language]]
name = "gdscript"
language-servers = ["godot"]
formatter = { command = "gdformat", args = ["-"] }
auto-format = true
language-id = "gdscript"
